name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
            node-version: '18.x'
            registry-url: 'https://registry.npmjs.org'
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rmarkdown", "knitr", "ggplot2", "reticulate"))'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build the JupyterLite site
        run: |
          cp README.md content
          jupyter lite build --contents content --output-dir dist
          cp deploy/netlify.toml dist
      - name: Download kuzu-wasm
        run: |
          npm view @kuzu/kuzu-wasm dist.tarball | xargs curl -o dist/package.tgz
          tar -xz -C dist -f dist/package.tgz && rm dist/package.tgz
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           path: docs
#       - name: Upload Artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: docs/_site
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     permissions:
#       pages: write
#       id-token: write
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4
    #   - name: Deploy to Netlify
    #     uses: nwtgck/actions-netlify@v3.0
    #     with:
    #       publish-dir: './dist'
    #       production-branch: master
    #       github-token: ${{ secrets.GITHUB_TOKEN }}
    #       deploy-message: "Deploy from GitHub Actions"
    #       enable-pull-request-comment: false
    #       enable-commit-comment: true
    #       overwrites-pull-request-comment: true
    #       enable-github-deployment: false
    #     env:
    #       NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    #       NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    #     timeout-minutes: 10